name: Solicitação de recursos
description: Sugerir um novo recurso ou melhoria para o software.
labels: [feature request]
body:
- type: checkboxes
  attributes:
    label: Existe alguma solicitação de recursos para isso?
    description: Por favor [pesquise aqui](https://github.com/Jexactyl-Brasil/Jexactyl-Brasil/issues?q=is%3Aissue) para ver se outra pessoa já sugeriu isto.
    options:
    - label: Pesquisei as questões existentes antes de abrir este pedido de recurso.
      required: true

- type: textarea
  attributes:
    label: Descreva a característica que você gostaria de ver.
    description: "Uma descrição clara e concisa da característica que você gostaria de ter acrescentado, e quais os problemas que isso resolveria."
  validations:
    required: true

- type: textarea
  attributes:
    label: Conteúdo adicional a esta solicitação.
    description: "Adicione qualquer outro conteúdo ou screenshots sobre o pedido de recursos."
  validations:
    required: false
