name: Build

on:
  push:
    branches:
      - "v*"
      - "v1*"
  pull_request:
    branches:
      - "v*"
      - "v1*"

jobs:
  ui:
    name: UI
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
    steps:
      - name: Verificação de codigo
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Instalar dependencias
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:production
