name: Build

on:
  push:
    branches:
      - "develop"
      - "1.0-develop"
      - "Beta-Test"
  pull_request:
    branches:
      - "develop"
      - "1.0-develop"

jobs:
  ui:
    name: UI
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
    steps:
      - name: Check-out de código
        uses: actions/checkout@v3

      - name: Configuração de Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Instalar dependências
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build
        run: yarn build:production
