name: Fixers

on:
  push:
    branches:
      - "develop"
      - "1.0-develop"
  pull_request:
    branches:
      - "develop"
      - "1.0-develop"

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
        
      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier fix
        run: pnpm run prettier --fix

      - name: Run ESLint fix
        run: pnpm run lint --fix
