name: Prettier
# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - 1.0-develop
      - Beta-Test

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Install npm v8
        run: npm i -g npm@8
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
        
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{tsx,css}
